### PR TITLE
[PR] JavaScript for accessible navigation work

### PR DESCRIPTION
**Pull request by jeremyfelt**
This is a pull request against #164, which applies a new accessible HTML structure to the main navigation on wsu.edu.

The state of the menu will be managed with `aria-expanded` on each `button` and `hidden` on each sub navigation `ul`:

* [x] Add `aria-expanded="false"` as the default state to each `button`
* [x] Add `hidden` as a default attribute to each sub navigation `ul`.
* [x] On `button` click, toggle `aria-expanded` between `true` and `false` on each `button` element in the navigation.
* [x] On `button` click, toggle the `hidden` attribute on each `.sub-navigation ul`

Keyboard behavior is based on [WAI-ARIA Authoring Practices for menus](https://www.w3.org/TR/wai-aria-practices-1.1/#menu).

## Enter
* [x] When focus is on a menuitem that has a submenu, opens the submenu and places focus on its first item.
* [x] Otherwise, activates the item and closes the menu.

## Space
* [x] When focus is on a menuitem that has a submenu, opens the submenu and places focus on its first item.
* [x] When focus is on a menuitem that does not have a submenu, activates the menuitem and closes the menu.

## Down Arrow
* [x] When focus is on a menuitem in a menubar, opens its submenu and places focus on the first item in the submenu.
* [x] When focus is in a menu, moves focus to the next item, optionally wrapping from the last to the first.

## Up Arrow
* [x] When focus is in a menu, moves focus to the previous item, optionally wrapping from the first to the last.

## Right Arrow
* [x] When focus is in a menubar, moves focus to the next item, optionally wrapping from the last to the first.
* [x] When focus is in a menu and on an item that does not have a submenu, moves focus to the next menuitem in the menubar.

## Left Arrow
* [x] When focus is in a menubar, moves focus to the previous item, optionally wrapping from the last to the first.
* [x] When focus is in a submenu of an item in a menubar, moves focus to the previous menuitem in the menubar.

## Escape
* [x] Close the menu that contains focus and return focus to the element or context from which the menu was opened.

## Tab
* [x] Moves focus to the next element in the tab sequence

## Shift + Tab
* [x] Moves focus to the previous element in the tab sequence

## Not Applicable

Items from the WAI-ARIA guide that are **not** currently applicable:

* **Up Arrow:** ~(Optional): When focus is on a menuitem in a menubar, opens its submenu and places focus on the last item in the submenu.~
* **Right Arrow:** ~When focus is in a menu and on an item that does not have a submenu, closes the submenu and any parent menus.~
* **Right Arrow:** ~When focus is in a menu and on an item that does not have a submenu, opens the submenu of that menuitem without moving focus into the submenu~
* **Left Arrow:** ~When focus is in a submenu of an item in a menubar, closes the submenu.~
* **Left Arrow:** ~When focus is in a submenu of an item in a menubar, opens the submenu of that menuitem without moving focus into the submenu~
* **Left Arrow:** ~When focus is in a submenu of an item in a menu, closes the submenu and returns focus to the parent menuitem.~
* **Home:** (Not applicable, wrapping is supported) ~If arrow key wrapping is not supported, moves focus to the first item in the current menu or menubar~
* **End:** (Not applicable, wrapping is supported) ~If arrow key wrapping is not supported, moves focus to the last item in the current menu or menubar~
* **Character keys:** (Maybe later) ~Move focus to the next menu item in the current menu whose label begins with that printable character~

### CODE REVIEW

**Comment by jeremyfelt** [comment]
@slocker3 @philcable Tagging you both to review. Check out the keyboard navigation and let me know how it feels / if I missed anything.

**Comment by slocker3** [comment]
Once in a submenu the up and down arrows only loop within the submenu–it appears that is expected behavior. This is new to me. I believe the checklist mentions the behavior `When focus is in a menu, moves focus to the next item, optionally wrapping from the last to the first.` Does _optionally mean that there isn't a standard approach to this @jeremyfelt ?

**Comment by jeremyfelt** [comment]
@slocker I don't know if it's standard. [The inclusive design article on menus](https://inclusive-components.design/menus-menu-buttons/) mentions it as well, though in reference to the WAI-ARIA authoring practices document.

I could go back and forth on it. Sometimes it seems helpful so that you don't have to reverse back to the beginning. It may be something that makes more sense if it's not in a "sub-menu", though I'm also not sure if my visual perception of it is muddying things vs what a screen reader user perceives.

**Comment by jeremyfelt** [comment]
> I don't know if it's standard. The inclusive design article on menus mentions it as well, though in reference to the WAI-ARIA authoring practices document.

The W3's [navigation menubar example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html) implements this as well.

**Comment by slocker3** [comment]
Good to merge from my perspective.

**Pull request merged**
