### PR TITLE
Start of HTML structure for main nav wsu.edu

### PR DESCRIPTION
**Pull request by slocker3**
add new style guide page - `home-nav.html`

### CODE REVIEW

**Comment by slocker3** [comment]
Mobile spine should show up at `989px` instead of `700px`. This will be consistent with the rest of WSU's web presence in the Spine.

**Comment by jeremyfelt** [comment]
Adding JS controls in #167 to merge into this before merging this into `master`.

**Comment by jeremyfelt** [comment]
#167 has been merged 🎉 

I'm going to start another branch off of this to add the nav the home page style guide and get the search area working as expected.

**Comment by jeremyfelt** [comment]
@slocker3 - Ball is back in your court I think. The markup and scripts are there and I moved some styles around. Now we'll need to make sure things are tightened up visually.

**Comment by jeremyfelt** [comment]
@slocker3 Things left:

* [ ] Add styles for the "close search" and "close navigation" buttons
* [ ] Fix hover styles in quick link navigation
* [ ] Confirm reversed styles on Top 10 page

**Comment by slocker3** [comment]
@jeremyfelt close buttons styled.

**Comment by jeremyfelt** [comment]
@slocker3 @philcable - Review please!

**Comment by slocker3** [comment]
@philcable @jeremyfelt I will commit a fix for the signature issue and the search icon. Phil good catch!

**Comment by jeremyfelt** [comment]
* Removed extra HTML characters in dc9fbdc and 89978d6
* Added focus styles for select and input in fa1bcc9

We're still using Spine 1.x on wsu.edu, so that's why the outline style was missing on focus. 🙃

**Pull request merged**
